#!/bin/bash

if [ -f /etc/init.d/bulckypi ]; then
    /etc/init.d/bulckypi force-stop
    sleep 2

    # Killing remaining process:
    if [ "`ps ax|grep bulckyPi.tcl|grep tclsh`" != "" ]; then
        for process in `ps ax|grep bulckyPi.tcl| grep tclsh| awk -F" " '{print $1}'`; do
            if [ "$process" != "" ]; then            
                kill -9 $process
            fi
        done
    fi


    for pid in "`ps ax|grep serveurLog.tcl |grep tclsh |awk -F " " '{print $1}'`"; do
        if [ "$pid" != "" ]; then
            kill -9 $pid
        fi
    done

    for pid in "`ps ax|grep serverPlugUpdate.tcl |grep tclsh |awk -F " " '{print $1}'`"; do
        if [ "$pid" != "" ]; then
            kill -9 $pid
        fi
    done

    for pid in "`ps ax|grep serverHisto.tcl |grep tclsh |awk -F " " '{print $1}'`"; do
        if [ "$pid" != "" ]; then
            kill -9 $pid
        fi
    done
fi

if [ ! -d /var/log/bucky ]; then
    mkdir /var/log/bulcky
    chown bulcky:bulcky /var/log/bulcky
fi

exit 0
