#!/bin/bash

if [ "$1" == "purge" ] || [ "$1" == "remove" ]; then
    if [ "`ps ax|grep bulckyCam.tcl|grep tclsh`" != "" ]; then
        for process in `ps ax|grep bulckyCam.tcl|grep tclsh|awk -F" " '{print $1}'`; do
            if [ "$process" != "" ]; then
                kill -9 $process
            fi
        done
    fi

    update-rc.d -f bulckycam remove >/dev/null 2>&1

    if [ -f /etc/init.d/bulckycam ]; then
        rm -Rf /etc/init.d/bulckycam
    fi

    sed -i "/bulcky ALL = (root) NOPASSWD: \/usr\/bin\/fswebcam/d" /etc/sudoers
    sed -i "/bulcky ALL = (root) NOPASSWD: \/etc\/init.d\/mjpg_streamer/d" /etc/sudoers
fi

