#!/bin/bash

if [ -f /etc/init.d/bulckycam ]; then
    update-rc.d bulckycam defaults
fi

if [ -d /opt/bulckycam ]; then
    chown -R bulcky:bulcky /opt/bulckycam
fi

if [ -f /etc/init.d/bulckycam ]; then
    chown bulcky:bulcky /etc/init.d/bulckycam 
    chmod 744 /etc/init.d/bulckycam
fi

if [ -f /etc/init.d/mjpg_streamer ];then
     chown bulcky:bulcky  /etc/init.d/mjpg_streamer
fi

if [ -d /etc/bulckycam ]; then
    chown -R bulcky:bulcky /etc/bulckycam
    chmod 744 /etc/init.d/mjpg_streamer
fi

find /etc/bulckypi/ -name "*-dist" 2>/dev/null|xargs rm 2>/dev/null; echo ""
/etc/init.d/bulckycam force-reload

if [  "`cat /etc/sudoers|grep bulcky|grep fswebcam`" == "" ]; then
    echo "bulcky ALL = (root) NOPASSWD: /usr/bin/fswebcam" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep bulcky|grep mjpg_streamer`" == "" ]; then
    echo "bulcky ALL = (root) NOPASSWD: /usr/bin/mjpg_streamer" >> /etc/sudoers
fi


