#!/bin/bash

if [ "$1" == "purge" ]; then
    if [ -d /var/www/bulcky ]; then
        echo " * Removing remaining file in /var/www/bulcky..."
        rm -Rf /var/www/bulcky
        echo "... OK"
    fi
fi

if [ "$1" == "purge" ] || [ "$1" == "remove" ]; then
    sed -i "/www-data ALL = (root) NOPASSWD: \/etc\/init.d\/bulckypi/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/chown/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/cat/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/sbin\/shutdown/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/sbin\/ifconfig/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/usr\/sbin\/iw/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/sbin\/ifup/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/mv/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/chmod/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/cp/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/usr\/bin\/apt-get/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/etc\/init.d\/dnsmasq/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/etc\/init.d\/isc-dhcp-server/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/date/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/usr\/sbin\/invoke-rc.d/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/usr\/bin\/tail/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/etc\/init.d\/lighttpd/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/usr\/bin\/dpkg/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/sbin\/hwclock/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/etc\/init.d\/ntp/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/sbin\/iwlist/d" /etc/sudoers
    sed -i "/www-data ALL = (root) NOPASSWD: \/bin\/mkdir/d" /etc/sudoers
fi

