#!/bin/bash

echo "  * Configuring/checking Bulcky environment..."

chown -R www-data:www-data /var/www/bulcky
chown -R www-data:www-data /var/www/mobile

if [  "`cat /etc/sudoers|grep www-data|grep ifconfig`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /sbin/ifconfig" >> /etc/sudoers
fi
 
if [  "`cat /etc/sudoers|grep www-data|grep iw`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /usr/sbin/iw" >> /etc/sudoers
fi
 
if [  "`cat /etc/sudoers|grep www-data|grep ifup`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /sbin/ifup" >> /etc/sudoers
fi
 
if [  "`cat /etc/sudoers|grep www-data|grep mv`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/mv" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep chmod`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/chmod" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep cp`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/cp" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep invoke-rc.d`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /usr/sbin/invoke-rc.d" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep apt-get`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /usr/bin/apt-get" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep isc-dhcp-server`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /etc/init.d/isc-dhcp-server" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep dnsmasq`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /etc/init.d/dnsmasq" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep ntp`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /etc/init.d/ntp" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep date`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/date" >> /etc/sudoers
fi

if [ "`cat /etc/sudoers|grep bulckypi|grep www-data`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /etc/init.d/bulckypi" >> /etc/sudoers
fi

if [ "`cat /etc/sudoers|grep chown|grep www-data`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/chown" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep cat`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /bin/cat" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep shutdown`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /sbin/shutdown" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep tail`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /usr/bin/tail" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep lighttpd`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /etc/init.d/lighttpd" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep dpkg`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /usr/bin/dpkg" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep hwclock`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /sbin/hwclock" >> /etc/sudoers
fi

if [  "`cat /etc/sudoers|grep www-data|grep iwlist`" == "" ]; then
    echo "www-data ALL = (root) NOPASSWD: /sbin/iwlist" >> /etc/sudoers
fi

if [ ! -f /tmp/bulcky_upgrade ]; then
    echo "  * Installing the Bulcky software..."
    /usr/bin/mysql --defaults-extra-file=/var/www/bulcky/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/bulcky/sql_install/user_bulcky.sql
    /usr/bin/mysql --defaults-extra-file=/var/www/bulcky/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/bulcky/sql_install/bulcky_fr.sql
    /usr/bin/mysql --defaults-extra-file=/var/www/bulcky/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 < /var/www/bulcky/sql_install/fake_log.sql
    /usr/bin/mysql --defaults-extra-file=/var/www/bulcky/sql_install/my-extra.cnf -h 127.0.0.1 --port=3891 bulcky -e "UPDATE sensors SET type=0  WHERE id > 1"
    echo "... OK"
else 
    echo "  * Upgrading the Bulcky databases, this may take several minutes, please be patient..."
    if [ -f /var/www/bulcky/sql_install/update_sql.sql ]; then
        /usr/bin/mysql --defaults-extra-file=/var/www/bulcky/sql_install/my-extra.cnf --force -h 127.0.0.1 --port=3891 < /var/www/bulcky/sql_install/update_sql.sql 2>/dev/null
    fi

    rm -f /tmp/bulcky_upgrade
    rm -f /var/www/bulcky/main/templates_c/*.ser 2>/dev/null
    echo "... OK"
fi

find /var/www/bulcky/ -name "*-dist"|xargs rm 2>/dev/null; echo ""


chmod 777 /var/www/bulcky/tmp


