#!/bin/bash 

# DefaultProduct=0x1F02 --> Annecy
# TargetProduct=0x14dc --> Annecy

if ! [ -f /etc/usb_modeswitch.d/12d1\:1f01 ]; then
    cat << EOF > /etc/usb_modeswitch.d/12d1\:1f01
# Huawei E353 (3.se) Ethernet Adapter
DefaultProduct=1f01
DefaultVendor= 0x12d1
TargetVendor=  0x12d1
TargetProduct= 0x14db
MessageContent="55534243123456780000000000000a11062000000000000100000000000000"
NoDriverLoading=1
EOF

fi

if [ "`ifconfig | /bin/grep eth1`" == "" ]; then
    /usr/sbin/usb_modeswitch -c /etc/usb_modeswitch.d/12d1\:1f01
    /etc/init.d/dnsmasq stop
fi

# * * * * * /bin/bash /home/bulcky/starteth1