#!/bin/bash

if [ -f /etc/init.d/bulckyraz ]; then   
    /etc/init.d/bulckyraz stop
    sleep 2

    # Killing remaining process:
    if [ "`ps ax|grep bulckyRAZ.tcl|grep tclsh`" != "" ]; then
        for process in `ps ax|grep bulckyRAZ.tcl| grep tclsh| awk -F" " '{print $1}'`; do
            if [ "$process" != "" ]; then
                kill -9 $process
            fi
        done
    fi
fi
exit 0
