#!/bin/bash

if [ -f /etc/cron.daily/bulcky ]; then
    chmod 755 /etc/cron.daily/bulcky
    chown root:root /etc/cron.daily/bulcky
fi

if [ -f /etc/cron.hourly/bulcky ]; then
    chmod 755 /etc/cron.hourly/bulcky
    chown root:root /etc/cron.hourly/bulcky
fi
	
if [ -f /etc/default/bulckycron ]; then
    chown root:root /etc/default/bulckycron
    chmod 744 /etc/default/bulckycron
fi

if [ ! -O /etc/logrotate.d/bulcky ] || [ ! -G /etc/logrotate.d/bulcky ]; then
    chown root:root /etc/logrotate.d/bulcky
    chmod 644 /etc/logrotate.d/bulcky
fi

if [ -d /etc/bulckyconf/postinst ]; then
    chown -R root:root /etc/bulckyconf/postinst
fi

if [ ! -d /var/log/bulcky ]; then
    mkdir /var/log/bulcky
    chown bulcky:bulcky /var/log/bulcky
fi

if [ -f /etc/bulckyconf/packages ]; then
    chown root:root /etc/bulckyconf/packages
fi

if [ -f /root/.bash_aliases ]; then
    chown root:root /root/.bash_aliases
fi

if [ -f /home/bulcky/.bash_aliases ]; then
    chown bulcky:bulcky /home/bulcky/.bash_aliases
fi

if [ -f /usr/bin/mjpg_streamer ]; then
    chmod 755 /usr/bin/mjpg_streamer
    chown bulcky:bulcky /usr/bin/mjpg_streamer
fi

if [ ! -d /home/bulcky/packages ]; then
    mkdir /home/bulcky/packages
    chown bulcky:bulcky /home/bulcky/packages
fi



if [ "`cat /etc/crontab|grep '[b]ulckycron'`" == "" ]; then
    echo "*/5 *   * * *   root    /bin/bash /etc/default/bulckycron" >> /etc/crontab
fi


if [ -f /VERSION ]; then
    VERSION="`cat /VERSION`"
else
    VERSION="000000"
fi


if [ "$VERSION" -lt  160411 ]; then
    echo "options 8192cu rtw_power_mgnt=0 rtw_enusbss=0" > /etc/modprobe.d/8192cu.conf

	cat << EOF > /etc/rc.local
#!/bin/bash 

#Case of an Access Point:
if [ "\`/bin/grep 10.0.0.100 /etc/network/interfaces\`" != "" ] && [ "\`/sbin/ifconfig wlan0\`" != "" ]; then
    #If it's not an Acces Point mode , deleteting captiv portal configuration:
    for i in \$(/sbin/iptables -t nat --line-numbers -L | /bin/grep ^[0-9] | /usr/bin/awk '{ print \$1 }' | /usr/bin/tac ); do /sbin/iptables -t nat -D PREROUTING \$i; done
fi

#Reconfigure wlan0 at boot:
if [ "\`/sbin/ifconfig wlan0\`" != "" ]; then
    if [ "\`/bin/grep 10.0.0.100 /etc/network/interfaces\`" == "" ]; then
        /bin/ping -c 1 8.8.8.8 >/dev/null 2>&1
        if [ \$? -ne 0 ]; then
            /sbin/ifdown --force wlan0
            sleep 1
            /sbin/ifup --force wlan0 
        fi
    fi
	/sbin/iwconfig wlan0 power off
	/sbin/iwconfig wlan0 rate 54M auto
fi

#To accelerate boot time, eth0 is not configured at boot time (due to the time DHCP uses to respond when a wire is not plugged).
#But we have to configure the interface if a wire is plugged:
if [ "\`cat /sys/class/net/eth0/carrier 2>/dev/null\`" == "1" ]; then
    /sbin/ifup --force eth0
else
    /sbin/ifdown --force eth0
fi

default="no"
if [ "\`cat /sys/class/net/eth0/carrier 2>/dev/null\`" == "1" ]; then
    gw="\`grep 'post-up /sbin/route add default gw' /etc/network/interfaces|grep eth0|sed -e 's/post-up //g'\`"
    if [ "\$gw" != "" ]; then
        default="yes"
        eval \$gw
    fi
fi

if [ "\`/sbin/ifconfig wlan0 2>/dev/null\`" != "" ] && [ "\$default" == "no" ]; then
    gw="\`grep 'post-up /sbin/route add default gw' /etc/network/interfaces|grep wlan0|sed -e 's/post-up //g'\`"
    if [ "\$gw" != "" ]; then
        eval \$gw
    fi
fi

#Configuration of the keymap in FR:
/usr/bin/loadkeys fr

if [ -f /etc/bulckyconf/system.conf ]; then
	. /etc/bulckyconf/system.conf
	if [ "\$CPU_GOUVERNOR" != "" ]; then
			echo "\$CPU_GOUVERNOR" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	fi
fi


CDATE="\`date +'%Y-%m-%d %H:%M:%S'\`"
URL_CONN="http://my.bulck.fr"
HOST_NAME="\`/sbin/ifconfig eth0 | /bin/grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'|/bin/sed -e 's/://g'\`"


if [ -f /VERSION ]; then
    version="version:\`cat /VERSION\`"
else
    version="version:000000"
fi

version="\$version:\`dpkg -l bulck*|grep \\"ii \\"|awk -F \\" \\" '{print \$2":"\$3}'|tr '\\n' ':'\`"
php_args="last_connect=\$CDATE&mac_address=\$HOST_NAME&version=\\"\$version\\""

wget -O - --quiet --retry-connrefused --waitretry=1 --timeout=20 -t 5 "\$URL_CONN/external/action.php?action=setobject&\$php_args"

echo "nameserver 208.67.222.222" > /etc/resolv.conf
echo "nameserver 208.67.222.220" >> /etc/resolv.conf


exit 0
EOF
	echo "160411" > /VERSION

    if [ "`cat /etc/lighttpd/.passwd|grep 'slf:Identification'`" == "" ]; then
        echo "slf:Identification:e4c15cb85e88bf26a6b400a4680d1d93" >> /etc/lighttpd/.passwd
        /etc/init.d/lighttpd force-reload
    fi
fi

if [ "$VERSION" -lt  160422 ]; then
    cat << EOF > /etc/rc.local
#!/bin/bash 

#Reconfigure wlan0 at boot:
if [ "\`/sbin/ifconfig wlan0\`" != "" ]; then
    if [ "\`/bin/grep 10.0.0.100 /etc/network/interfaces\`" == "" ]; then
        /bin/ping -c 1 8.8.8.8 >/dev/null 2>&1
        if [ \$? -ne 0 ]; then
            /sbin/ifdown --force wlan0
            sleep 1
            /sbin/ifup --force wlan0 
        fi
    fi
    /sbin/iwconfig wlan0 power off
    /sbin/iwconfig wlan0 rate 54M auto
fi

#Configure eth1 for the access box :
if [ "\`grep eth1 /etc/network/interfaces \`" == "" ]; then
    echo "" >> /etc/network/interfaces
    echo "#IFACE ETH1" >> /etc/network/interfaces
    echo "allow-hotplug eth1" >> /etc/network/interfaces
    echo "iface eth1 inet dhcp" >> /etc/network/interfaces

    /sbin/ifdown --force eth1 
    sleep 2
    /sbin/ifup --force eth1 
fi


#To accelerate boot time, eth0 is not configured at boot time (due to the time DHCP uses to respond when a wire is not plugged).
#But we have to configure the interface if a wire is plugged:
if [ "\`cat /sys/class/net/eth0/carrier 2>/dev/null\`" == "1" ] || [ "\`cat /etc/network/interfaces |grep '^iface eth0' | grep static\`" != "" ]; then
    /sbin/ifup --force eth0
else
    /sbin/ifdown --force eth0
fi


default="no"
if [ "\`cat /sys/class/net/eth0/carrier 2>/dev/null\`" == "1" ]; then
    gw="\`grep 'post-up /sbin/route add default gw' /etc/network/interfaces|grep eth0|sed -e 's/post-up //g'\`"
    if [ "\$gw" != "" ]; then
        default="yes"
        eval \$gw
    fi
fi

if [ "\`/sbin/ifconfig wlan0 2>/dev/null\`" != "" ] && [ "\$default" == "no" ]; then
    gw="\`grep 'post-up /sbin/route add default gw' /etc/network/interfaces|grep wlan0|sed -e 's/post-up //g'\`"
    if [ "\$gw" != "" ]; then
        eval \$gw
    fi
fi

#Configuration of the keymap in FR:
/usr/bin/loadkeys fr

if [ -f /etc/bulckyconf/system.conf ]; then
    . /etc/bulckyconf/system.conf
    if [ "\$CPU_GOUVERNOR" != "" ]; then
            echo "\$CPU_GOUVERNOR" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    fi
fi


CDATE="\`date +'%Y-%m-%d %H:%M:%S'\`"
URL_CONN="http://my.bulck.fr"
HOST_NAME="\`/sbin/ifconfig eth0 | /bin/grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'|/bin/sed -e 's/://g'\`"


if [ -f /VERSION ]; then
    version="version:\`cat /VERSION\`"
else
    version="version:000000"
fi

version="\$version:\`dpkg -l bulck*|grep \\"ii \\"|awk -F \\" \\" '{print \$2":"\$3}'|tr '\\n' ':'\`"
php_args="last_connect=\$CDATE&mac_address=\$HOST_NAME&version=\\"\$version\\""

wget -O - --quiet --retry-connrefused --waitretry=1 --timeout=20 -t 5 "\$URL_CONN/external/action.php?action=setobject&\$php_args"

echo "nameserver 208.67.222.222" > /etc/resolv.conf
echo "nameserver 208.67.222.220" >> /etc/resolv.conf


exit 0
EOF

cat << EOF > /etc/default/ifplugd 
# This file may be changed either manually or by running dpkg-reconfigure.
#
# N.B.: dpkg-reconfigure deletes everything from this file except for
# the assignments to variables INTERFACES, HOTPLUG_INTERFACES, ARGS and
# SUSPEND_ACTION.  When run it uses the current values of those variables
# as their default values, thus preserving the administrator's changes.
#
# This file is sourced by both the init script /etc/init.d/ifplugd and
# the udev script /lib/udev/ifplugd.agent to give default values.
# The init script starts ifplugd for all interfaces listed in
# INTERFACES, and the udev script starts ifplugd for all interfaces
# listed in HOTPLUG_INTERFACES. The special value all starts one
# ifplugd for all interfaces being present.
INTERFACES="eth0 eth1"
HOTPLUG_INTERFACES=""
ARGS="-q -f -u0 -d10 -w -I"
SUSPEND_ACTION="stop"
EOF

    echo "160422" > /VERSION
fi



if [ "$VERSION" -lt  160609 ]; then
	if [ -f /etc/lighttpd/lighttpd.conf ] && [ -f /etc/lighttpd/lighttpd.conf.https ]; then

cat << EOF > /etc/lighttpd/lighttpd.conf
server.modules = (
   "mod_access",
   "mod_alias",
   "mod_compress",
   "mod_redirect",
   "mod_auth"
   #"mod_rewrite",
)

server.document-root        = "/var/www"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80

auth.backend = "htdigest"
auth.backend.htdigest.userfile = "/etc/lighttpd/.passwd"
auth.debug = 2

index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"

\$HTTP["url"] =~ "/" {
url.redirect = ("^/\$" => "/bulcky/")
}


\$HTTP["url"] =~ "^/" {
    auth.require = ( "" =>
    (
    "method" => "digest",
    "realm" => "Identification",
    "require" => "valid-user"
    )
    )
}
EOF

cat << EOF > /etc/lighttpd/lighttpd.conf.https
server.modules = (
   "mod_access",
   "mod_alias",
   "mod_compress",
   "mod_redirect",
   "mod_auth"
   #"mod_rewrite",
)

server.document-root        = "/var/www"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80

auth.backend = "htdigest"
auth.backend.htdigest.userfile = "/etc/lighttpd/.passwd"
auth.debug = 2

index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"

\$SERVER["socket"] == ":443" {
  ssl.engine = "enable"
  ssl.pemfile = "/etc/lighttpd/ssl/bulcky.pem"
}


\$HTTP["scheme"] == "http" {
    # capture vhost name with regex conditiona -> %0 in redirect pattern
    # must be the most inner block to the redirect rule
    \$HTTP["host"] =~ ".*" {
        url.redirect = (".*" => "https://%0\$0")
    }
}

\$HTTP["url"] =~ "/" {
    url.redirect = ("^/\$" => "/bulcky/")
}


\$HTTP["url"] =~ "^/" {
    auth.require = ( "" =>
    (
    "method" => "digest",
    "realm" => "Identification",
    "require" => "valid-user"
    )
    )
}
EOF

    fi


    if [ -f /etc/lighttpd/lighttpd.conf ] && [ -f /etc/lighttpd/lighttpd.conf.base ]; then
cat << EOF > /etc/lighttpd/lighttpd.conf.base
server.modules = (
   "mod_access",
   "mod_alias",
   "mod_compress",
   "mod_redirect",
   "mod_auth"
   #"mod_rewrite",
)

server.document-root        = "/var/www"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80

auth.backend = "htdigest"
auth.backend.htdigest.userfile = "/etc/lighttpd/.passwd"
auth.debug = 2

index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"

\$HTTP["url"] =~ "/" {
    url.redirect = ("^/\$" => "/bulcky/")
}


\$HTTP["url"] =~ "^/" {
    auth.require = ( "" =>
    (
    "method" => "digest",
    "realm" => "Identification",
    "require" => "valid-user"
    )
    )
}
EOF


cat << EOF > /etc/lighttpd/lighttpd.conf
server.modules = (
   "mod_access",
   "mod_alias",
   "mod_compress",
   "mod_redirect",
   "mod_auth"
   #"mod_rewrite",
)

server.document-root        = "/var/www"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80

auth.backend = "htdigest"
auth.backend.htdigest.userfile = "/etc/lighttpd/.passwd"
auth.debug = 2

index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"

\$SERVER["socket"] == ":443" {
  ssl.engine = "enable"
  ssl.pemfile = "/etc/lighttpd/ssl/bulcky.pem"
}


\$HTTP["scheme"] == "http" {
    # capture vhost name with regex conditiona -> %0 in redirect pattern
    # must be the most inner block to the redirect rule
    \$HTTP["host"] =~ ".*" {
        url.redirect = (".*" => "https://%0\$0")
    }
}

\$HTTP["url"] =~ "/" {
    url.redirect = ("^/\$" => "/bulcky/")
}


\$HTTP["url"] =~ "^/" {
    auth.require = ( "" =>
    (
    "method" => "digest",
    "realm" => "Identification",
    "require" => "valid-user"
    )
    )
}
EOF

    fi

    cat << EOF > /etc/rc.local
#!/bin/bash 

#Reconfigure wlan0 at boot:
if [ "\`/sbin/ifconfig wlan0\`" != "" ]; then
    if [ "\`/bin/grep 10.0.0.100 /etc/network/interfaces\`" == "" ]; then
        /bin/ping -c 1 8.8.8.8 >/dev/null 2>&1
        if [ \$? -ne 0 ]; then
            /sbin/ifdown --force wlan0
            sleep 1
            /sbin/ifup --force wlan0 
        fi
    else
        /etc/init.d/isc-dhcp-server restart
        /etc/init.d/dnsmasq restart
        /etc/init.d/hostapd restart
    fi
    /sbin/iwconfig wlan0 power off
fi

#Configure eth1 for the access box :
if [ "\`grep eth1 /etc/network/interfaces \`" == "" ]; then
    echo "" >> /etc/network/interfaces
    echo "#IFACE ETH1" >> /etc/network/interfaces
    echo "allow-hotplug eth1" >> /etc/network/interfaces
    echo "iface eth1 inet dhcp" >> /etc/network/interfaces

    /sbin/ifdown --force eth1 
    sleep 2
    /sbin/ifup --force eth1 
fi


#To accelerate boot time, eth0 is not configured at boot time (due to the time DHCP uses to respond when a wire is not plugged).
#But we have to configure the interface if a wire is plugged:
if [ "\`cat /sys/class/net/eth0/carrier 2>/dev/null\`" == "1" ] || [ "\`cat /etc/network/interfaces |grep '^iface eth0' | grep static\`" != "" ]; then
    /sbin/ifup --force eth0
else
    /sbin/ifdown --force eth0
fi


default="no"
if [ "\`cat /sys/class/net/eth0/carrier 2>/dev/null\`" == "1" ]; then
    gw="\`grep 'post-up /sbin/route add default gw' /etc/network/interfaces|grep eth0|sed -e 's/post-up //g'\`"
    if [ "\$gw" != "" ]; then
        default="yes"
        eval \$gw
    fi
fi

if [ "\`/sbin/ifconfig wlan0 2>/dev/null\`" != "" ] && [ "\$default" == "no" ]; then
    gw="\`grep 'post-up /sbin/route add default gw' /etc/network/interfaces|grep wlan0|sed -e 's/post-up //g'\`"
    if [ "\$gw" != "" ]; then
        eval \$gw
    fi
fi

#Configuration of the keymap in FR:
/usr/bin/loadkeys fr

if [ -f /etc/bulckyconf/system.conf ]; then
    . /etc/bulckyconf/system.conf
    if [ "\$CPU_GOUVERNOR" != "" ]; then
            echo "\$CPU_GOUVERNOR" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    fi
fi


CDATE="\`date +'%Y-%m-%d %H:%M:%S'\`"
URL_CONN="http://my.bulck.fr"
HOST_NAME="\`/sbin/ifconfig eth0 | /bin/grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}'|/bin/sed -e 's/://g'\`"


if [ -f /VERSION ]; then
    version="version:\`cat /VERSION\`"
else
    version="version:000000"
fi

version="\$version:\`dpkg -l bulck*|grep \\"ii \\"|awk -F \\" \\" '{print \$2":"\$3}'|tr '\\n' ':'\`"
php_args="last_connect=\$CDATE&mac_address=\$HOST_NAME&version=\\"\$version\\""

wget -O - --quiet --retry-connrefused --waitretry=1 --timeout=20 -t 5 "\$URL_CONN/external/action.php?action=setobject&\$php_args"

echo "nameserver 208.67.222.222" > /etc/resolv.conf
echo "nameserver 208.67.222.220" >> /etc/resolv.conf


exit 0
EOF

   echo "160609" > /VERSION
fi











