#!/bin/bash

if [ -f /etc/cron.daily/bulcky ]; then
    chmod 755 /etc/cron.daily/bulcky
    chown root:root /etc/cron.daily/bulcky
fi

if [ -f /etc/cron.hourly/bulcky ]; then
    chmod 755 /etc/cron.hourly/bulcky
    chown root:root /etc/cron.hourly/bulcky
fi
	
if [ -f /etc/default/bulckycron ]; then
    chown root:root /etc/default/bulckycron
    chmod 744 /etc/default/bulckycron
fi

if [ ! -O /etc/logrotate.d/bulcky ] || [ ! -G /etc/logrotate.d/bulcky ]; then
    chown root:root /etc/logrotate.d/bulcky
    chmod 644 /etc/logrotate.d/bulcky
fi

if [ -d /etc/bulckyconf/postinst/ ]; then
    chown -R root:root /etc/bulckyconf/postinst
fi

if [ ! -d /var/log/bulcky ]; then
    mkdir /var/log/bulcky
    chown bulcky:bulcky /var/log/bulcky
fi

if [ -f /etc/bulckyconf/packages ]; then
    chown root:root /etc/bulckyconf/packages
fi

if [ -f /root/.bash_aliases ]; then
    chown root:root /root/.bash_aliases
fi

if [ -f /home/bulcky/.bash_aliases ]; then
    chown bulcky:bulcky /home/bulcky/.bash_aliases
fi

if [ -f /usr/bin/mjpg_streamer ]; then
    chmod 755 /usr/bin/mjpg_streamer
fi


if [ "`cat /etc/crontab|grep '[b]ulckycron'`" == "" ]; then
    echo "*/1 *   * * *   root    /bin/bash /etc/default/bulckycron" >> /etc/crontab
fi


if [ -f /VERSION ]; then
    VERSION="`cat /VERSION`"
else
    VERSION="000000"
fi


if [ $VERSION -lt 151201 ]; then
    echo "First VERSION!"
fi

