#!/bin/bash

if [ -f /etc/init.d/bulckycam ]; then
    /etc/init.d/bulckycam stop
    sleep 2

    # Killing remaining process:
    if [ "`ps ax|grep bulckyCam.tcl|grep tclsh`" != "" ]; then
        for process in `ps ax|grep bulckyCam.tcl| grep tclsh| awk -F" " '{print $1}'`; do
            if [ "$process" != "" ]; then            
                kill -9 $process
            fi
        done
    fi
fi

exit 0
