#! /bin/sh
### BEGIN INIT INFO
# Provides:          bulckycam
# Required-Start:    $all 
# Required-Stop:     $all 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start bulckycam daemon at boot time
# Description:       Enable bulckycam service provided by daemon.
### END INIT INFO


PATH="/sbin:/bin:/usr/sbin:/usr/bin" 

DAEMONUSER="bulcky"
DEAMON_NAME="bulckycam"

d_start () {
        echo "Starting system $DEAMON_NAME service"
		if [ "`ps ax|grep bulckyCam.tcl|grep tclsh`" != "" ]; then
            echo -n  "\n[ ok ] $DEAMON_NAME service is already running.\n"
            exit 0
        else
			sudo -u $DAEMONUSER nohup /usr/bin/tclsh "/opt/bulckycam/bulckyCam.tcl" "/etc/bulckycam/conf.xml" >>/var/log/bulcky/bulcky-services.log 2>&1 &
			sleep 4
		fi
}

d_stop () {
        echo "Stopping system $DEAMON_NAME Daemon"
        for pid in "`ps ax|grep bulckyCam.tcl |grep tclsh |awk -F " " '{print $1}'`"; do
            if [ "$pid" != "" ]; then
                kill -9 $pid
            fi
        done
        sleep 1
}

case "$1" in

        start|stop)
                d_${1}
                ;;

        restart|reload|force-reload)
                        d_stop
                        d_start
                ;;
        force-stop)
                d_stop
                ;;
        status)
                if [ "`ps ax|grep bulckyCam.tcl|grep tclsh`" != "" ]; then
                    echo "[ ok ] $DEAMON_NAME service is running..."
                    exit 0
                else 
                    echo "[ fail ] $DEAMON_NAME service is not running..."
                    exit 1
                fi
                ;;
        *)
                echo "Usage: /etc/init.d/$DEAMON_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
                exit 1
                ;;
esac
exit 0
